# Generated by Django 3.2.5 on 2022-05-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_auto_20220427_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
