# Generated by Django 3.2.5 on 2022-05-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0004_auto_20220507_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='name',
            field=models.CharField(default='Bed Time', max_length=128),
        ),
    ]
